export const NFL_TEAMS = [
  { value: "ARI", label: "Arizona Cardinals", division: "NFC West", color: "#97233f" },
  { value: "ATL", label: "Atlanta Falcons", division: "NFC South", color: "#a71930" },
  { value: "BAL", label: "Baltimore Ravens", division: "AFC North", color: "#241773" },
  { value: "BUF", label: "Buffalo Bills", division: "AFC East", color: "#00338d" },
  { value: "CAR", label: "Carolina Panthers", division: "NFC South", color: "#0085ca" },
  { value: "CHI", label: "Chicago Bears", division: "NFC North", color: "#0b162a" },
  { value: "CIN", label: "Cincinnati Bengals", division: "AFC North", color: "#000000" },
  { value: "CLE", label: "Cleveland Browns", division: "AFC North", color: "#fb4f14" },
  { value: "DAL", label: "Dallas Cowboys", division: "NFC East", color: "#002244" },
  { value: "DEN", label: "Denver Broncos", division: "AFC West", color: "#002244" },
  { value: "DET", label: "Detroit Lions", division: "NFC North", color: "#005a8b" },
  { value: "GB", label: "Green Bay Packers", division: "NFC North", color: "#203731" },
  { value: "HOU", label: "Houston Texans", division: "AFC South", color: "#03202f" },
  { value: "IND", label: "Indianapolis Colts", division: "AFC South", color: "#002c5f" },
  { value: "JAX", label: "Jacksonville Jaguars", division: "AFC South", color: "#000000" },
  { value: "KC", label: "Kansas City Chiefs", division: "AFC West", color: "#e31837" },
  { value: "LV", label: "Las Vegas Raiders", division: "AFC West", color: "#a5acaf" },
  { value: "LAC", label: "Los Angeles Chargers", division: "AFC West", color: "#002244" },
  { value: "LA", label: "Los Angeles Rams", division: "NFC West", color: "#002244" },
  { value: "MIA", label: "Miami Dolphins", division: "AFC East", color: "#008e97" },
  { value: "MIN", label: "Minnesota Vikings", division: "NFC North", color: "#4f2683" },
  { value: "NE", label: "New England Patriots", division: "AFC East", color: "#002244" },
  { value: "NO", label: "New Orleans Saints", division: "NFC South", color: "#9f8958" },
  { value: "NYG", label: "New York Giants", division: "NFC East", color: "#0b2265" },
  { value: "NYJ", label: "New York Jets", division: "AFC East", color: "#203731" },
  { value: "PHI", label: "Philadelphia Eagles", division: "NFC East", color: "#004953" },
  { value: "PIT", label: "Pittsburgh Steelers", division: "AFC North", color: "#000000" },
  { value: "SF", label: "San Francisco 49ers", division: "NFC West", color: "#aa0000" },
  { value: "SEA", label: "Seattle Seahawks", division: "NFC West", color: "#002244" },
  { value: "TB", label: "Tampa Bay Buccaneers", division: "NFC South", color: "#d50a0a" },
  { value: "TEN", label: "Tennessee Titans", division: "AFC South", color: "#002244" },
  { value: "WAS", label: "Washington Commanders", division: "NFC East", color: "#773141" }
];
